/* automatically generated by rust-bindgen 0.57.0 */

extern "C" {
    pub fn get_windowBackgroundColor(r: *mut f64, g: *mut f64, b: *mut f64, a: *mut f64);
}
extern "C" {
    pub fn get_labelColor(r: *mut f64, g: *mut f64, b: *mut f64, a: *mut f64);
}
extern "C" {
    pub fn get_controlBackgroundColor(r: *mut f64, g: *mut f64, b: *mut f64, a: *mut f64);
}
extern "C" {
    pub fn get_secondaryLabelColor(r: *mut f64, g: *mut f64, b: *mut f64, a: *mut f64);
}
extern "C" {
    pub fn get_tertiaryLabelColor(r: *mut f64, g: *mut f64, b: *mut f64, a: *mut f64);
}
extern "C" {
    pub fn get_quaternaryLabelColor(r: *mut f64, g: *mut f64, b: *mut f64, a: *mut f64);
}
extern "C" {
    pub fn get_textColor(r: *mut f64, g: *mut f64, b: *mut f64, a: *mut f64);
}
extern "C" {
    pub fn get_placeholderTextColor(r: *mut f64, g: *mut f64, b: *mut f64, a: *mut f64);
}
extern "C" {
    pub fn get_selectedTextColor(r: *mut f64, g: *mut f64, b: *mut f64, a: *mut f64);
}
extern "C" {
    pub fn get_textBackgroundColor(r: *mut f64, g: *mut f64, b: *mut f64, a: *mut f64);
}
extern "C" {
    pub fn get_selectedTextBackgroundColor(r: *mut f64, g: *mut f64, b: *mut f64, a: *mut f64);
}
extern "C" {
    pub fn get_keyboardFocusIndicatorColor(r: *mut f64, g: *mut f64, b: *mut f64, a: *mut f64);
}
extern "C" {
    pub fn get_unemphasizedSelectedTextColor(r: *mut f64, g: *mut f64, b: *mut f64, a: *mut f64);
}
extern "C" {
    pub fn get_unemphasizedSelectedTextBackgroundColor(
        r: *mut f64,
        g: *mut f64,
        b: *mut f64,
        a: *mut f64,
    );
}
extern "C" {
    pub fn get_linkColor(r: *mut f64, g: *mut f64, b: *mut f64, a: *mut f64);
}
extern "C" {
    pub fn get_separatorColor(r: *mut f64, g: *mut f64, b: *mut f64, a: *mut f64);
}
extern "C" {
    pub fn get_selectedContentBackgroundColor(r: *mut f64, g: *mut f64, b: *mut f64, a: *mut f64);
}
extern "C" {
    pub fn get_unemphasizedSelectedContentBackgroundColor(
        r: *mut f64,
        g: *mut f64,
        b: *mut f64,
        a: *mut f64,
    );
}
extern "C" {
    pub fn get_selectedMenuItemTextColor(r: *mut f64, g: *mut f64, b: *mut f64, a: *mut f64);
}
extern "C" {
    pub fn get_gridColor(r: *mut f64, g: *mut f64, b: *mut f64, a: *mut f64);
}
extern "C" {
    pub fn get_headerTextColor(r: *mut f64, g: *mut f64, b: *mut f64, a: *mut f64);
}
extern "C" {
    pub fn get_controlAccentColor(r: *mut f64, g: *mut f64, b: *mut f64, a: *mut f64);
}
extern "C" {
    pub fn get_controlColor(r: *mut f64, g: *mut f64, b: *mut f64, a: *mut f64);
}
extern "C" {
    pub fn get_controlTextColor(r: *mut f64, g: *mut f64, b: *mut f64, a: *mut f64);
}
extern "C" {
    pub fn get_disabledControlTextColor(r: *mut f64, g: *mut f64, b: *mut f64, a: *mut f64);
}
extern "C" {
    pub fn get_selectedControlColor(r: *mut f64, g: *mut f64, b: *mut f64, a: *mut f64);
}
extern "C" {
    pub fn get_selectedControlTextColor(r: *mut f64, g: *mut f64, b: *mut f64, a: *mut f64);
}
extern "C" {
    pub fn get_alternateSelectedControlTextColor(
        r: *mut f64,
        g: *mut f64,
        b: *mut f64,
        a: *mut f64,
    );
}
extern "C" {
    pub fn get_scrubberTexturedBackgroundColor(r: *mut f64, g: *mut f64, b: *mut f64, a: *mut f64);
}
extern "C" {
    pub fn get_windowFrameTextColor(r: *mut f64, g: *mut f64, b: *mut f64, a: *mut f64);
}
extern "C" {
    pub fn get_underPageBackgroundColor(r: *mut f64, g: *mut f64, b: *mut f64, a: *mut f64);
}
extern "C" {
    pub fn get_findHighlightColor(r: *mut f64, g: *mut f64, b: *mut f64, a: *mut f64);
}
extern "C" {
    pub fn get_highlightColor(r: *mut f64, g: *mut f64, b: *mut f64, a: *mut f64);
}
extern "C" {
    pub fn get_shadowColor(r: *mut f64, g: *mut f64, b: *mut f64, a: *mut f64);
}
extern "C" {
    pub fn get_systemBrownColor(r: *mut f64, g: *mut f64, b: *mut f64, a: *mut f64);
}
extern "C" {
    pub fn get_systemGrayColor(r: *mut f64, g: *mut f64, b: *mut f64, a: *mut f64);
}
extern "C" {
    pub fn get_systemGreenColor(r: *mut f64, g: *mut f64, b: *mut f64, a: *mut f64);
}
extern "C" {
    pub fn get_systemIndigoColor(r: *mut f64, g: *mut f64, b: *mut f64, a: *mut f64);
}
extern "C" {
    pub fn get_systemOrangeColor(r: *mut f64, g: *mut f64, b: *mut f64, a: *mut f64);
}
extern "C" {
    pub fn get_systemPinkColor(r: *mut f64, g: *mut f64, b: *mut f64, a: *mut f64);
}
extern "C" {
    pub fn get_systemPurpleColor(r: *mut f64, g: *mut f64, b: *mut f64, a: *mut f64);
}
extern "C" {
    pub fn get_systemRedColor(r: *mut f64, g: *mut f64, b: *mut f64, a: *mut f64);
}
extern "C" {
    pub fn get_systemTealColor(r: *mut f64, g: *mut f64, b: *mut f64, a: *mut f64);
}
extern "C" {
    pub fn get_systemYellowColor(r: *mut f64, g: *mut f64, b: *mut f64, a: *mut f64);
}
extern "C" {
    pub fn get_systemBlueColor(r: *mut f64, g: *mut f64, b: *mut f64, a: *mut f64);
}
